[package]
name = "donut"
version = "0.1.0"
authors = ["drip"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "*"

[lib]
name = "donut"
path = "src/lib.rs"
